### ISSUE TITLE
Double-conversion compatible output?

### ISSUE THREAD

**Issue by ColinH** [ulfjack/ryu#30]
Hi, after seeing the benchmarks we are looking into using Ryu instead of the double-conversion library for `double`-to-string conversions in our [JSON library](https://github.com/taocpp/json).

For that we don't need flexible output formats like in #27, however we would prefer the output to be formatted like in the double-conversion library, i.e. use scientific notation only for large numbers.

After changing Ryu to use `0.0` instead of `0E0`, and `e` instead of `E`, here are some examples of how Ryu compares to double-conversion:

```
= 0.0
= -0.0
! 1.0 1e0
! -1.0 -1e0
! 1.5 1.5e0
! -1.5 -1.5e0
! 0.0001 1e-4
! -0.0001 -1e-4
! 3.1416 3.1416e0
! 42.0 4.2e1
! -42.0 -4.2e1
! 0.1 1e-1
! 10000000000.0 1e10
! -10000000000.0 -1e10
! -10000000000.0 -1e10
= -1e-10
! 12340000000.0 1.234e10
= 1.234e-10
= 1.79769e308
= 2.22507e-308
= -1.79769e308
= -2.22507e-308
= 5e-324
= 2.225073858507201e-308
= 2.2250738585072014e-308
= 1.7976931348623157e308
! 18446744073709552000.0 1.8446744073709552e19
! -9223372036854776000.0 -9.223372036854776e18
! 0.9868011474609375 9.868011474609375e-1
= 1.23e36
! 45913141877270640000.0 4.591314187727064e19
= 2.225073858507201e-308
= 1.7976931348623157e308
= 2.2250738585072014e-308
= 2.225073858507201e-308
! 0.9999999999999999 9.999999999999999e-1
! 1.0000000000000002 1.0000000000000002e0
! 72057594037927930.0 7.205759403792793e16
! 72057594037927940.0 7.205759403792794e16
! 9223372036854775000.0 9.223372036854775e18
! 9223372036854776000.0 9.223372036854776e18
= 1.0141204801825834e31
= 1.0141204801825835e31
= 5.708990770823839e45
= 5.70899077082384e45
! 300.0 3e2
```

A leading `=` means that the two coincide, a leading `!` means that they don't, with the first number being from double-conversion, and the second from Ryu.

Any thoughts on this subject, or hints on how to go about it?

Thank you!

**Comment by ColinH** [comment]
Ok, thanks. Do I understand correctly that only `Step 5: Print the decimal representation` needs to be changed?

Also, why would `DIGIT_TABLE` be disabled, assuming that it's usually a speed-up, are there any deeper reasons than to give the choice to save a bit of memory?

**Comment by ulfjack** [comment]
That's right.

I don't know why anyone would disable DIGIT_TABLE - at the time I couldn't convince myself to drop the original implementation, and I'm also not sure if it's standards compliant C. If everyone is in agreement then I'd be happy to drop the old code.

**Comment by ColinH** [comment]
Is there a particular part that you believe might not be standards compliant?

(And, just out of curiosity, how much of a speed-up is the DIGIT_TABLE - if there is a simple answer?)

**Comment by ColinH** [comment]
Btw, is there a particular reason why you always use `memcpy()` on the `digit_table` except for one place where you use two manual assignments for the single characters?

**Comment by ulfjack** [comment]
About 17% and 33% faster with the table for float and double respectively.

I believe you mean https://github.com/ulfjack/ryu/blob/master/ryu/d2s.c#L493 - the reason for that is that the decimal dot goes between those two digits.

**Comment by ColinH** [comment]
Right, thank you, hadn't seen that yet. And thanks for the numbers, 33% is a lot!

(It might of course be less with cold caches, but then again it doesn't really matter how slow it is when you don't do it often enough to have the digit table in the cache.)

**Comment by ColinH** [comment]
One more question (thank you for your patience), the extra 32bit optimisation in Step 5 of `d2s_buffered()` for X86 and ARM is just that, an optimisation that could also be removed (if you only care about 32bit compatibility, but not about optimising for it)?

**Comment by ulfjack** [comment]
Yes, you can look at the history of the file - it was added in commit 4a273a3a0cbf430e4016df4a127bd6cf7e56e2bc. The original code didn't do that.

**Comment by mitchblank** [comment]
> I would suggest implementing the same interface as the double-conversion library.

Something like that would be nice... or at least a close approximation to it.

FWIW, in the project I work on, we only use double-conversion's `DoubleToAscii(d, SHORTEST, ...)` API which effectively transforms a `double` into a tuple of {`bool negative`, `char digits[17]`, `unsigned length`,`int point`} -- after that I do all the rendering of stuff like placing the decimal point, putting in zeros, exponents, etc.  (I also take care of the non-finite numbers myself, so I don't use its handling NaN/Infinity/etc) This is important in my case because I often have extra information about significant (decimal) figures so I often need to handle final rounding and presentation myself.

It looks like algorithm-wise ryu would work great for my needs, but right now the library does too much.  I just want the decimal digits and the metadata about where the decimal place is in relation to them.

**Comment by ColinH** [comment]
@ulfjack Thank you, good to have one's understanding confirmed :-)

**Comment by mitchblank** [comment]
Looking at the code a bit more closely, I'm thinking the ideal "low-level" ryu API (replacing the functionality from `DoubleToAscii` would be to take everything from after the call to `copy_special_str()` and before the `Step 5: Print the decimal representation.`  So you'd have something like:
```
struct ryu_shortest_representation_double {
  uint64_t decimal;
  int32_t exponent;
};
extern struct ryu_shortest_representation_double ryu_find_shortest_representation_double(uint64_t ieee754_bits);

struct ryu_shortest_representation_double {
  uint32_t decimal;
  int32_t exponent;
};
extern struct ryu_shortest_representation_single ryu_find_shortest_representation_single(uint32_t ieee754_bits);
```

At least on the x86-64 ABI those structs would be small enough that the'll just be returned in a `%rax`/`%rdx` pair, so no expense there.  There isn't any need to return the sign, since that is trivial to find from the integer you passed in.

In my code that is relying on `DoubleToAscii()` I could easily just render the decimal value into the `digits[]` array, and `point` should be computable from the length of that and `.exponent`.

The current APIs like `f2s()` would be easy to implement on that layer as well -- In fact I think it would clean things up a bit since you could make a separate .c file that contained that rendering code and make things like `DIGIT_TABLE[]` static to that.  

Thoughts?

**Comment by ColinH** [comment]
Update, I've experimented a bit with a stripped-down version (removed most `#ifdef`s) which you can find at https://github.com/taocpp/json/blob/ryu/include/tao/json/external/ryu.hpp.

The main part is that Step 5 is now a separate function, and there's an alternative that creates the usual non-scientific notation, and there's an `if` that chooses between the two just like double-conversion does (which, with a few cleanups, solves my original question).

Now if you look at `d2s_scientific_step5()` you'll see that it takes an additional argument (beyond your `decimal` and `exponent`), the `olength`, since it is used both before and in the function.

Perhaps it's possible to remove this input parameter from Step 5 without sacrificing performance, I haven't thought about how defining `exp` without `olength` would work for Step 5, if we're lucky it's simple.

**Comment by ulfjack** [comment]
There's also #35.

**Comment by ColinH** [comment]
I'll close this issue because I managed to get it to work in a modified copy of Ryu, the Ryu library itself is adding the foundation for more flexible output formatting, and my feeling is that further or more in-depth questions and issues should be discussed separately. Thanks everybody!
