### ISSUE TITLE
Some of the results of RyuFloat are different from that of JDK

### ISSUE THREAD

**Issue by wenshao** [ulfjack/ryu#41]
```java
        Random random = new Random();

        for (int i = 0; i < 1000 * 1000 * 10; ++i) {
            float value = random.nextFloat();

            String str1 = Float.toString(value);
            String str2 = RyuFloat.floatToString(value);

            if (!str1.equals(str2)) {
                System.out.println(str1 + " -> " + str2);
                assertTrue(Float.parseFloat(str1) == Float.parseFloat(str2));
            }
        }
```

different results:
```
0.33007812 -> 0.33007813
0.17382812 -> 0.17382813
0.0063476562 -> 0.0063476563
0.43945312 -> 0.43945313
0.33789062 -> 0.33789063
0.0043945312 -> 0.0043945313
0.036132812 -> 0.036132813
0.47851562 -> 0.47851563
0.17382812 -> 0.17382813
0.47851562 -> 0.47851563
0.26757812 -> 0.26757813
0.40039062 -> 0.40039063
0.36914062 -> 0.36914063
0.43945312 -> 0.43945313
0.18945312 -> 0.18945313
0.043945312 -> 0.043945313
0.40039062 -> 0.40039063
0.020507812 -> 0.020507813
0.040039062 -> 0.040039063
0.36132812 -> 0.36132813
0.37695312 -> 0.37695313
0.29882812 -> 0.29882813
0.36132812 -> 0.36132813
0.29882812 -> 0.29882813
0.36914062 -> 0.36914063
0.41601562 -> 0.41601563
```

**Comment by DrorHarari** [comment]
I have found a similar difference between ryu's results and the gcc printf
when using the format %+16e - I too found a difference in the last digit.
It appears that gcc's printf approach was to take extra digit from the
actual number (which usually have much more digits) while ryu just
truncates the digit outside of the precision range.

In my case I did not find any precision lost  though because the result is
different, there is an impact on the unit tests.

Dror


On Jul 31, 2018 7:48 PM, "温绍锦" <notifications@github.com> wrote:

        Random random = new Random();

        for (int i = 0; i < 1000 * 1000 * 10; ++i) {
            float value = random.nextFloat();

            String str1 = Float.toString(value);
            String str2 = RyuFloat.floatToString(value);

            if (!str1.equals(str2)) {
                System.out.println(str1 + " -> " + str2);
                assertTrue(Float.parseFloat(str1) == Float.parseFloat(str2));
            }
        }

different results:

0.33007812 -> 0.33007813
0.17382812 -> 0.17382813
0.0063476562 -> 0.0063476563
0.43945312 -> 0.43945313
0.33789062 -> 0.33789063
0.0043945312 -> 0.0043945313
0.036132812 -> 0.036132813
0.47851562 -> 0.47851563
0.17382812 -> 0.17382813
0.47851562 -> 0.47851563
0.26757812 -> 0.26757813
0.40039062 -> 0.40039063
0.36914062 -> 0.36914063
0.43945312 -> 0.43945313
0.18945312 -> 0.18945313
0.043945312 -> 0.043945313
0.40039062 -> 0.40039063
0.020507812 -> 0.020507813
0.040039062 -> 0.040039063
0.36132812 -> 0.36132813
0.37695312 -> 0.37695313
0.29882812 -> 0.29882813
0.36132812 -> 0.36132813
0.29882812 -> 0.29882813
0.36914062 -> 0.36914063
0.41601562 -> 0.41601563

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ulfjack/ryu/issues/41>, or mute the thread

**Comment by ulfjack** [comment]
The initial report is a known issue (#8).

I didn't double-check all the values you provided, but here's RyuFloat debugging output for the first value 0.33007812f (you can edit RyuFloat.java line 86 and then run it as a main class to get this output):
```
IN=111110101010010000000000000000
   S=+ E=-25 M=11075584
Exact values
  m =44302336
  E =-1
  d+=330078139901161193847656250
  d =330078125000000000000000000
  d-=330078110098838806152343750
  e2=-27
44302336 * 5^27 / 10^18 = 44302336 * 5^9 / 2^18
Actual values
  d+=330078139
  d =330078125
  d-=330078110
  last removed=0
  e10=-9
  d+10=false
  d-10=false
Actual values after loop
  d+=33007813
  d =33007812
  d-=33007811
  last removed=5
  e10=-9
  d+10=false
  d-10=false
  output=33007813
  output_length=8
  output_exponent=-1
0.33007813 0.33007812
```

This is a bit much, but these are the most important lines:
```
  d+=330078139901161193847656250
  d =330078125000000000000000000
  d-=330078110098838806152343750
```

I'm using BigInteger to compute the exact decimal representation of the number itself, as well as the lower and upper bounds. For a complete explanation, I'll have to refer to the paper, but - briefly - the lower and upper bounds give the range within which the output _must_ be in order to be round-trip safe, i.e., if you want the original number back, you _must_ output a number that's between the bounds.

Here, the bounds are:
```
0.330078110098838806152343750 <= x <= 0.330078139901161193847656250
```

Both Ryu's output and the OpenJDK output numbers that are between the bounds. This is easy to see if you write them in the same column:
```
upper:   0.330078139901161193847656250
Ryu:     0.33007813
OpenJDK: 0.33007812
lower:   0.330078110098838806152343750
```

In fact, these are the only shortest decimal floating point numbers in this interval. But since we have a choice, which one should we take? We now look at the exact number, which is:
```
upper:   0.330078139901161193847656250
Ryu:     0.33007813
exact:   0.330078125000000000000000000
OpenJDK: 0.33007812
lower:   0.330078110098838806152343750
```

As you can see, the exact number has a 5 next, followed by zeroes. In this case, the Ryu's specification says that we need to round to even, so it should round down and output 0.33007812. It's not doing that right now.

**Comment by ulfjack** [comment]
As for printf, it doesn't use the same specification as Ryu - Ryu always outputs the shortest possible value that correctly converts back to the original number, and it should round-even in case of a tie.

**Comment by ulfjack** [comment]
I pushed a fix for 32-bit floats. Please follow #8 if you're interested in a complete resolution.

**Comment by plokhotnyuk** [comment]
Shouldn't it be fixed for 64-bit doubles too?

**Comment by ulfjack** [comment]
Yes, it definitely needs to be fixed for doubles as well.

I don't understand your second statement, I'm afraid. Maybe the code has changed?

**Comment by plokhotnyuk** [comment]
Never-mind about my 2nd statement, I have misunderstood those statements.

Comparing with C version I see that the following statement possible was missed in Java: `dvIsTrailingZeros &= lastRemovedDigit == 0` for both rounding loops.
